name: Prepare Libraries

on:
  workflow_dispatch: # Ручной запуск, так как это тяжелая операция сборки зависимостей

jobs:
  prepare:
    name: Build Dependencies
    runs-on: windows-2022
    env:
      Platform: x64
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          path: tdesktop
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Clone AyuGram Source Code
        uses: actions/checkout@v4
        with:
          repository: AyuGram/AyuGramDesktop
          path: tdesktop
          submodules: recursive

      - name: Setup MSVC (Visual Studio 2022)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Create Build Directories
        run: |
          if not exist Libraries mkdir Libraries
          if not exist ThirdParty mkdir ThirdParty
        shell: cmd

      - name: Restore Cache
        id: cache-libs
        uses: actions/cache@v4
        with:
          path: |
            Libraries
            ThirdParty
          # Ключ кэша зависит от содержимого скрипта подготовки, где указаны версии библиотек
          key: prepare-libs-${{ hashFiles('tdesktop/Telegram/build/prepare/win.bat') }}

      - name: Run Prepare Script
        # Запуск производится из корневой директории (родительской для tdesktop), как требует логика скрипта
        run: |
          tdesktop\Telegram\build\prepare\win.bat
        shell: cmd

      - name: Upload Libraries Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prepared-Libraries
          path: Libraries/
          retention-days: 1


      - name: Upload Libraries Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prepared-ThirdParty
          path: ThirdParty/
          retention-days: 1
